### ISSUE TITLE
avxsynth does not compile anymore with gcc 4.7.0

### ISSUE THREAD

**Issue by fleger** [avxsynth/avxsynth#14]
I'm using gcc 4.7.0 with Arch Linux 64bit.
Build fails with the following error:

```
g++ -pthread -Wall -Wno-unused -fPIC -g -D_REENTRANT -I./src -I../../include -I../common/include -I../common/include/audio -I../common/include/distrib -I../common/include/convert -I../common/include/core -I../common/include/filters -I../common/include/source  -c src/filters/focus.cpp -o src/filters/focus.o
src/filters/focus.cpp: In function ‘void avxsynth::AFH_YUY2_C(unsigned char*, int, int, int, int)’:
src/filters/focus.cpp:522:6: error: redeclaration of ‘unsigned char y’
src/filters/focus.cpp:507:11: error: ‘int y’ previously declared here
```

It used to build fine with gcc 4.6.3.
