### ISSUE TITLE
GCC4.7 regression in 0a3c10a78d6243b8d839bdc70bfd5133479ea905

### ISSUE THREAD

**Issue by sl1pkn07** [avxsynth/avxsynth#49]
../../avxsynth/core/src/core/plugins.cpp: In function ‘bool avxsynth::MyLoadLibrary(const char_, void__, bool, avxsynth::IScriptEnvironment_)’:
../../avxsynth/core/src/core/plugins.cpp:101:25: error: ‘getcwd’ was not declared in this scope

fix add "#include < unistd.h >" in avxsynth/core/src/core/plugins.cp
